import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${inter.className} h-full antialiased bg-white text-slate-900 dark:bg-slate-950 dark:text-slate-100 selection:bg-indigo-200/40 selection:text-slate-900`}
      >
        {/* App background aesthetic (non-interactive) */}
        <div className="pointer-events-none fixed inset-0 -z-10">
          {/* soft radial color washes */}
          <div className="absolute -top-24 -left-24 h-96 w-96 rounded-full bg-gradient-to-tr from-rose-300/35 via-fuchsia-300/25 to-transparent blur-3xl" />
          <div className="absolute -bottom-24 -right-24 h-[28rem] w-[28rem] rounded-full bg-gradient-to-tr from-indigo-300/25 via-cyan-300/25 to-transparent blur-3xl" />

          {/* subtle dotted texture (masked) */}
          <div className="absolute inset-0 opacity-40 [mask-image:radial-gradient(transparent_0,black_65%)]">
            <div className="h-full w-full bg-[radial-gradient(rgba(17,24,39,0.04)_1px,transparent_1.6px)] bg-[length:18px_18px] dark:bg-[radial-gradient(rgba(226,232,240,0.06)_1px,transparent_1.6px)]" />
          </div>

          {/* fine light beams */}
          <div className="absolute left-10 right-10 top-0 h-px bg-gradient-to-r from-transparent via-indigo-300/60 to-transparent" />
          <div className="absolute left-16 right-16 bottom-0 h-px bg-gradient-to-r from-transparent via-emerald-300/50 to-transparent" />
        </div>

        {/* App content */}
        <div className="min-h-screen">{children}</div>
      </body>
    </html>
  );
}
